version: "3.9"

services:
  db:
    image: mysql
    restart: always
    volumes:
      - db_store_memes:/var/lib/mysql_new
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'

volumes:
  db_store_memes: