"""create model MemeGrade.

Revision ID: cada71afd6c4
Revises: 0c6a82dea18a
Create Date: 2022-07-01 22:09:23.037068

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "cada71afd6c4"
down_revision = "0c6a82dea18a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meme_grade",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("meme_id", sa.Integer(), nullable=False),
        sa.Column("grade", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(["meme_id"], ["meme.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "meme_id", name="unique_together_user_meme"),
    )
    op.alter_column(
        "meme", "url", existing_type=mysql.VARCHAR(length=300), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "meme", "url", existing_type=mysql.VARCHAR(length=300), nullable=True
    )
    op.drop_table("meme_grade")
    # ### end Alembic commands ###
